const propertyImages = [
  "/assets/imoveis/imovel2.webp",
  "/assets/imoveis/imovel4.webp",
  "/assets/imoveis/imovel5.webp",
  "/assets/imoveis/imovel6.webp",
];

const propertiesVenda = [
  {
    id: "apartamento-3-quartos-copacabana",
    title: "Apartamento de 3 Quartos em Copacabana",
    price: 1200000,
    type: "venda" as const,
    address: "Copacabana, Rio de Janeiro - RJ",
    bedrooms: 3,
    bathrooms: 2,
    area: 120,
    imageUrl: propertyImages[0],
    featured: true,
  },
  {
    id: "casa-4-quartos-jardins",
    title: "Casa de 4 Quartos no Jardins",
    price: 2500000,
    type: "venda" as const,
    address: "Jardins, São Paulo - SP",
    bedrooms: 4,
    bathrooms: 3,
    area: 280,
    imageUrl: propertyImages[1],
    featured: true,
  },
  {
    id: "cobertura-duplex-leblon",
    title: "Cobertura Duplex no Leblon",
    price: 4800000,
    type: "venda" as const,
    address: "Leblon, Rio de Janeiro - RJ",
    bedrooms: 4,
    bathrooms: 4,
    area: 320,
    imageUrl: propertyImages[2],
    featured: true,
  },
  {
    id: "apartamento-2-quartos-ipanema",
    title: "Apartamento de 2 Quartos em Ipanema",
    price: 1800000,
    type: "venda" as const,
    address: "Ipanema, Rio de Janeiro - RJ",
    bedrooms: 2,
    bathrooms: 2,
    area: 95,
    imageUrl: propertyImages[3],
    featured: true,
  },
  {
    id: "casa-condominio-alphaville",
    title: "Casa em Condomínio em Alphaville",
    price: 3200000,
    type: "venda" as const,
    address: "Alphaville, Barueri - SP",
    bedrooms: 5,
    bathrooms: 4,
    area: 450,
    imageUrl: propertyImages[0],
    featured: true,
  },
  {
    id: "apartamento-studio-vila-madalena",
    title: "Studio na Vila Madalena",
    price: 650000,
    type: "venda" as const,
    address: "Vila Madalena, São Paulo - SP",
    bedrooms: 1,
    bathrooms: 1,
    area: 45,
    imageUrl: propertyImages[1],
    featured: true,
  },
];

export { propertyImages };
export default propertiesVenda; 